modLoader="javafml"
loaderVersion="[36,)"
license="MPL-2.0"
issueTrackerURL="https://github.com/Tslat/SmartBrainLib/issues"

[[mods]]
modId="smartbrainlib"
version="1.9"
displayName="SmartBrainLib"
logoFile="logo.png"
authors="Tslat"
description='''
A library mod for smarter Brains and easier usage of the Brain system.
'''

[[dependencies.smartbrainlib]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"
[[dependencies.smartbrainlib]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,)"
ordering="NONE"
side="BOTH"
