modLoader="javafml"
loaderVersion="[36,)"
license="MPL 2.0"
issueTrackerURL="https://github.com/Tslat/SmartBrainLib/issues"

[[mods]]
modId="smartbrainlib"
version="${file.jarVersion}"
displayName="SmartBrainLib"
#updateJSONURL="https://change.me.example.invalid/updates.json"
logoFile="logo.png"
authors="Tslat"
description='''
A library mod for smarter Brains and easier usage of the Brain system.
'''
